on: [push, pull_request, workflow_dispatch]
env:
  CYPRESS_CACHE_FOLDER: cypress/cache

jobs:
  e2e-testing:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: exercices/steps
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('**/package-lock.json') }}
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14'
          cache: 'npm'
          cache-dependency-path: 'exercices/steps/package-lock.json'
      - run: npm ci
      - name: run exercice 01 e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npx nx run exercice01-solution-e2e:e2e
          start: npx nx run nest-server:serve
          working-directory: exercices/steps
          install: false
      - name: run exercice 02 e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npx nx run exercice02-solution-e2e:e2e
          start: npx nx run nest-server:serve
          working-directory: exercices/steps
          install: false
      - name: run exercice 03 e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npx nx run exercice03-solution-e2e:e2e
          start: npx nx run nest-server:serve
          working-directory: exercices/steps
          install: false
      - name: run exercice 04 e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npx nx run exercice04-solution-e2e:e2e
          start: npx nx run nest-server:serve
          working-directory: exercices/steps
          install: false
      - name: run exercice 05 e2e testing
        uses: cypress-io/github-action@v2
        with:
          command: npx nx run exercice05-solution-e2e:e2e
          start: npx nx run nest-server:serve
          working-directory: exercices/steps
          install: false




